src/SFA.DAS.AssessorService.Web/ViewModels/ExternalApi/ExternalApiDetailsViewModel.cs
using SFA.DAS.AssessorService.Api.Types.Models.Azure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SFA.DAS.AssessorService.Web.ViewModels.ExternalApi
{
    public class ExternalApiDetailsViewModel
    {
        public IEnumerable<AzureUser> PrimaryContacts { get; set; }

        public AzureUser LoggedInUser { get; set; }

        public IEnumerable<AzureSubscription> SubscriptionsToShow { get; set; }

    }
}

src/SFA.DAS.AssessorService.Web/Controllers/ExternalApiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SFA.DAS.AssessorService.Api.Types.Models.Azure;
using SFA.DAS.AssessorService.Application.Api.Client.Azure;
using SFA.DAS.AssessorService.Settings;
using SFA.DAS.AssessorService.Web.StartupConfiguration;
using SFA.DAS.AssessorService.Web.ViewModels.ExternalApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SFA.DAS.AssessorService.Web.Controllers
{
    //  [Authorize(Policy = Policies.ExternalApiAccess)]
    [Authorize]
    public class ExternalApiController : Controller
    {
        private readonly ILogger<ExternalApiController> _logger;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IWebConfiguration _webConfiguration;
        private readonly IAzureApiClient _apiClient;

        public ExternalApiController(ILogger<ExternalApiController> logger, IHttpContextAccessor contextAccessor, IWebConfiguration webConfiguration, IAzureApiClient apiClient)
        {
            _logger = logger;
            _contextAccessor = contextAccessor;
            _webConfiguration = webConfiguration;
            _apiClient = apiClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var ukprn = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.portal.com/ukprn")?.Value;
            var email = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.portal.com/mail")?.Value;
            var productId = _webConfiguration.AzureApiAuthentication.ProductId;

            var users = await GetAllUsers(ukprn, email);
            var loggedInUser = users.Where(u => u.Email.Equals(email, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();

            var subscriptionsToShow = users.SelectMany(u => u.Subscriptions.Where(s => s.IsActive && s.ProductId == productId)).ToList();
            var primaryContacts = subscriptionsToShow.SelectMany(s => users.Where(u => u.Id == s.UserId)).ToList();

            // For now we show all subscriptions from the logged in user and the 'productId' subscription if the primary contact has it too.
            if (loggedInUser != null)
            {
                subscriptionsToShow.AddRange(loggedInUser.Subscriptions.Where(s => s.IsActive));
            }

            var viewmodel = new ExternalApiDetailsViewModel
            {
                LoggedInUser = loggedInUser,
                PrimaryContacts = primaryContacts,
                SubscriptionsToShow = subscriptionsToShow.GroupBy(s => s.Id).Select(s => s.First())
            };

            return View(viewmodel);
        }

        private async Task<IEnumerable<AzureUser>> GetAllUsers(string ukprn, string email)
        {
            var users = new List<AzureUser>();

            var ukprnUsers = await _apiClient.GetUserDetailsByUkprn(ukprn, true);

            if (ukprnUsers != null)
            {
                users.AddRange(ukprnUsers);
            }

            var emailuser = await _apiClient.GetUserDetailsByEmail(email, true);

            if (emailuser != null && !users.Any(u => u.AzureId == emailuser.AzureId))
            {
                users.Add(emailuser);
            }

            return users;
        }


        [HttpPost]
        public async Task<IActionResult> EnableAccess()
        {
            var ukprn = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.portal.com/ukprn")?.Value;
            var username = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")?.Value;

            var result = await _apiClient.CreateUser(ukprn, username);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveAccess(AzureUser viewModel)
        {
            var ukprn = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.portal.com/ukprn")?.Value;
            var username = _contextAccessor.HttpContext.User.Claims.FirstOrDefault(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")?.Value;

            if (viewModel.IsActive)
            {
                await _apiClient.DeleteUser(viewModel.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RenewPrimaryKey(string subscriptionId, string userId)
        {
            var user = await _apiClient.RegeneratePrimarySubscriptionKey(subscriptionId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RenewSecondaryKey(string subscriptionId, string userId)
        {
            var user = await _apiClient.RegenerateSecondarySubscriptionKey(subscriptionId);
            return RedirectToAction("Index");
        }
    }
}

src/SFA.DAS.AssessorService.Web/Views/ExternalApi/Index.cshtml
@using SFA.DAS.AssessorService.Web.ViewModels.ExternalApi;
@model ExternalApiDetailsViewModel
@{
    ViewBag.Title = "External API Details";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-one-third">
        <a class="link-back" asp-controller="Dashboard" asp-action="Index">Home</a>
    </div>
</div>

<div class="grid-row">
    <div class="column-full">
        <h1 class="heading-large">External API Details</h1>
        @if (!Model.PrimaryContacts.Any())
        {
            <span class="form-hint">By enabling access you will be the primary contact.</span>

            <form asp-action="EnableAccess" asp-controller="ExternalApi" method="post">
                <button class="button" type="submit">Enable</button>
            </form>
        }
        else
        {
            <div class="grid-row">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Ukprn</th>
                            <th>Email</th>
                            <th>Access</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model.PrimaryContacts)
                        {
                            <tr>
                                <td data-label="Ukprn">@user.Ukprn</td>
                                <td data-label="Email">@user.Email</td>
                                <td data-label="Access">@(user.IsActive ? "Enabled" : "Disabled")</td>
                                <td>
                                    <form asp-action="RemoveAccess" asp-controller="ExternalApi" method="post">
                                        @Html.Hidden("AzureId", user.AzureId, new { @id = "AzureId" })
                                        @Html.Hidden("State", user.State, new { @id = "State" })
                                        <button class="button" type="submit">Remove access</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            @if (Model.SubscriptionsToShow.Any())
            {
                <div class="grid-row">
                    <div class="column-two-thirds">
                        <h1 class="heading-large">Subscriptions</h1>
                    </div>

                    @foreach (var subscription in Model.SubscriptionsToShow)
                    {
                        var subscriptionUser = Model.PrimaryContacts.Where(pc => pc.Id == subscription.UserId).FirstOrDefault() ?? Model.LoggedInUser;
                        <div class="column-full form-group">
                            <h2>
                                <label class="form-label">
                                    <span class="heading-medium">@subscription.ProductId</span>
                                    <span class="form-hint">@subscriptionUser?.Email</span>
                                </label>
                            </h2>
                            <h3 class="heading-small">Api endpoint</h3>
                            <span class="code">@subscription.ApiEndPointUrl</span>
                            <h3 class="heading-small">Subscription key</h3>
                            <form asp-action="RenewPrimaryKey" asp-controller="ExternalApi" asp-route-subscriptionId="@subscription.Id" asp-route-userId="@subscription.UserId" method="post">
                                <span class="code">@subscription.PrimaryKey</span>
                                <input type="submit" value="Renew" class="button" />
                            </form>
                            @*
                                <h3 class="heading-small">Secondary subscription key</h3>
                                <form asp-action="RenewSecondaryKey" asp-controller="ExternalApi" asp-route-subscriptionId="@subscription.Id" asp-route-userId="@subscription.UserId" method="post">
                                    <span class="code">@subscription.SecondaryKey</span>
                                    <input type="submit" value="Renew" class="button" />
                                </form>
                            *@
                        </div>
                    }

                </div>
            }
        }
    </div>
</div>