src/SFA.DAS.AssessorService.Web.Staff/Controllers/CertificateAmendController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.Logging;
using SFA.DAS.AssessorService.Domain.Consts;
using SFA.DAS.AssessorService.Web.Staff.Infrastructure;
using SFA.DAS.AssessorService.Web.Staff.ViewModels;

namespace SFA.DAS.AssessorService.Web.Staff.Controllers
{
    [Authorize]
    public class CertificateAmendController : CertificateBaseController
    {
        public CertificateAmendController(ILogger<CertificateAmendController> logger,
            IHttpContextAccessor contextAccessor,
            ApiClient apiClient) : base(logger, contextAccessor, apiClient)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Check(Guid certificateId, string searchString, int page)
        {
            var viewModel = await LoadViewModel<CertificateCheckViewModel>(certificateId, "~/Views/CertificateAmend/Check.cshtml");
            var viewResult = (viewModel as ViewResult);
            var certificateCheckViewModel = viewResult.Model as CertificateCheckViewModel;

            certificateCheckViewModel.Page = page;
            certificateCheckViewModel.SearchString = searchString;


            var options = await ApiClient.GetOptions(certificateCheckViewModel.StandardCode);
            TempData["HideOption"] = !options.Any();

            return viewModel;
        }

        [HttpPost(Name = "Check")]
        public async Task<IActionResult> ConfirmAndSubmit(CertificateCheckViewModel vm)
        {
            if (vm.Status == CertificateStatus.Printed ||
                vm.Status == CertificateStatus.Reprint)
            {
                return RedirectToAction("Index", "DuplicateRequest",
                    new
                    {
                        certificateId = vm.Id, redirectToCheck = vm.RedirectToCheck,
                        Uln = vm.Uln,
                        StdCode = vm.StandardCode,                     
                        Page = vm.Page,
                        SearchString = vm.SearchString
                    });
            }
            else
            {
                return RedirectToAction("Index", "Comment",
                    new
                    {
                        certificateId = vm.Id, redirectToCheck = vm.RedirectToCheck,
                        Uln = vm.Uln,
                        StdCode = vm.StandardCode,
                        Page = vm.Page,                       
                        SearchString = vm.SearchString
                    });
            }
        }
    }
}

src/SFA.DAS.AssessorService.Web.Staff/Controllers/SearchController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SFA.DAS.AssessorService.Api.Types.Models;
using SFA.DAS.AssessorService.Domain.Paging;
using SFA.DAS.AssessorService.Web.Staff.Infrastructure;

namespace SFA.DAS.AssessorService.Web.Staff.Controllers
{
    [Authorize(Roles = Domain.Roles.OperationsTeam + "," + Domain.Roles.CertificationTeam)]
    public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private readonly ApiClient _apiClient;
        private readonly ISessionService _sessionService;

        public SearchController(ILogger<SearchController> logger, ApiClient apiClient, ISessionService sessionService)
        {
            _logger = logger;
            _apiClient = apiClient;
            _sessionService = sessionService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("results")]
        public async Task<IActionResult> Results(string searchString, int page = 1)
        {
            var searchResults = await _apiClient.Search(searchString, page);
            var searchViewModel = new SearchViewModel
            {
                StaffSearchResult = searchResults,
                SearchString = searchString,
                Page = page
            };

            return View(searchViewModel);
        }

        [HttpGet("select")]
        public async Task<IActionResult> Select(int stdCode,
            long uln,
            string searchString,
            int page = 1,
            bool allLogs = false,
            int? batchNumber = null)
        {
            var learner = await _apiClient.GetLearner(stdCode, uln, allLogs);

            var vm = new LearnerDetailViewModel
            {
                Learner = learner,
                SearchString = searchString,
                Page = page,
                ShowDetail = !allLogs,
                BatchNumber = batchNumber
            };

            return View(vm);
        }
    }

    public class LearnerDetailViewModel
    {
        public LearnerDetail Learner { get; set; }
        public string SearchString { get; set; }
        public int Page { get; set; }
        public bool ShowDetail { get; set; }
        public int? BatchNumber { get; set; }
    }

    public class SearchViewModel
    {
        public string SearchString { get; set; }
        public int Page { get; set; }
        public StaffSearchResult StaffSearchResult { get; set; }
    }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/Date.cshtml
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.CertificateDateViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Apprenticeship achievement date";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-date-form" type="post" asp-controller="CertificateDate">
            <input type="hidden" name="fullDate" id="fullDate" class="date-input" />
            @Html.HiddenFor(c => c.Id)
            @Html.HiddenFor(m => m.StartDate)
            <input type="hidden" name="WarningShown" id="WarningShown" value="@Model.WarningShown" />

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
            <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="error-summary-list">
                    <li><a sfa-validation-for="Date"></a></li>
                    <li><a sfa-validation-for="Day"></a></li>
                    <li><a sfa-validation-for="Month"></a></li>
                    <li><a sfa-validation-for="Year"></a></li>
                    <li><a sfa-validation-for="ReasonForChange"></a></li>
                </ul>
            </div>
            }

            <div sfa-anyvalidationerror-class="after-error-summary">
                <div id="Date">
                    <h1 class="heading-medium">
                        @*<span class="heading-secondary">@Model.GivenNames @Model.FamilyName</span>*@
                        What's the apprenticeship achievement date?
                    </h1>
                </div>

                <div class="form-group error-message-container" sfa-anyvalidationerror-class="form-group-error">
                    <span class="form-hint">
                        For example, 15 10 2017
                    </span>
                    <div class="form-date">
                        <div class="form-group form-group-day">
                            <label for="Day">Day</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Day" sfa-validationerror-class="form-control-error" asp-for="Day" type="text" maxlength="2" />
                        </div>

                        <div class="form-group form-group-month">
                            <label for="Month">Month</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Month" sfa-validationerror-class="form-control-error" asp-for="Month" type="text" maxlength="2" />
                        </div>

                        <div class="form-group form-group-year">
                            <label for="Year">Year</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Year" sfa-validationerror-class="form-control-error" asp-for="Year" type="text" maxlength="4" />
                        </div>
                    </div>
                </div>

                <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                    <label for="ReasonForChange">
                        <span class="form-label-bold">Reason for change</span>
                        <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                        <span class="error-message" asp-validation-for="ReasonForChange"></span>
                    </label>
                    <textarea class="form-control form-control-3-4" rows="5" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange"></textarea>
                </div>
            </div>

            <details>
                <summary><span class="summary">What’s an apprenticeship achievement date?</span></summary>
                <div class="panel panel-border-narrow" id="what-is-the-apprenticeship-achievement-date">
                    <p>
                        The achievement date is the date you confirmed the apprentice completed the apprenticeship.
                    </p>
                </div>
            </details>
            <button type="submit" class="button">Continue</button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/CertificateAmend/_DateScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/FirstName.cshtml
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.Private.CertificateFirstNameViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Apprentice's first name";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-firstname-form js-disable-on-submit" method="post" asp-action="FirstName" asp-controller="CertificatePrivateFirstName">
            @Html.HiddenFor(c => c.Id)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                    <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                        There is a problem
                    </h2>
                    <ul class="error-summary-list">
                        <li><a sfa-validation-for="FirstName"></a></li>
                        <li><a sfa-validation-for="ReasonForChange"></a></li>
                    </ul>
                </div>
            }

                <div sfa-anyvalidationerror-class="after-error-summary">
                    <h1 class="heading-large">
                        What's the apprentice's first name?
                    </h1>

                    <div class="form-group" sfa-validation-for="FirstName" sfa-validationerror-class="form-group-error">
                        <label for="FirstName">
                            <span class="form-label-bold visually-hidden">First name</span>
                            <span class="form-hint">
                                For example, Karla
                            </span>
                            <span class="error-message" asp-validation-for="FirstName"></span>
                        </label>
                        <input class="form-control" name="FirstName" sfa-validation-for="FirstName" sfa-validationerror-class="form-control-error" asp-for="FirstName" type="text" maxlength="100" />
                    </div>

                    <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                        <label for="ReasonForChange">
                            <span class="form-label-bold">Reason for change</span>
                            <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                            <span class="error-message" asp-validation-for="ReasonForChange"></span>
                        </label>
                        <textarea class="form-control form-control-3-4" rows="5" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange"></textarea>
                    </div>
                </div>

            <button type="submit" class="button">Continue</button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/CertificateAmend/_FirstNameScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/Grade.cshtml
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.CertificateGradeViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Grade apprentice achieved";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">

        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-grade-form" type="post" asp-controller="CertificateGrade">
            @Html.HiddenFor(c => c.Id)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
            <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There's a problem
                </h2>
                <ul class="error-summary-list">
                    <li><a sfa-validation-for="SelectedGrade"></a></li>
                    @*<li><a href="#Pass">You need to specify an achievement grade for this apprentice</a></li>*@
                    <li><a sfa-validation-for="ReasonForChange"></a></li>
                </ul>
            </div>
            }

            <div sfa-anyvalidationerror-class="after-error-summary">
                <div id="SelectedGrade">
                    <h1 class="heading-medium">
                        @*<span class="heading-secondary">@Model.GivenNames @Model.FamilyName</span>*@
                        What grade did the apprentice achieve?
                    </h1>
                    <div class="error-message-container" sfa-validation-for="SelectedGrade" sfa-validationerror-class="form-group-error">
                        <span class="error-message" asp-validation-for="SelectedGrade"></span>
                    </div>
                </div>
                <div class="form-group" sfa-validation-for="SelectedGrade" sfa-validationerror-class="form-group-error">
                    @foreach (var grade in Model.Grades)
                    {
                        <div class="multiple-choice">
                            <input asp-for="SelectedGrade" id="@grade.Text.Replace(" ", "_")" type="radio" value="@grade.Text" />
                            <label for="@grade.Text.Replace(" ", "_")">
                                @grade.Text
                            </label>
                        </div>
                    }
                </div>
                <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                    <label for="ReasonForChange">
                        <span class="form-label-bold">Reason for change</span>
                        <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                        <span class="error-message" asp-validation-for="ReasonForChange"></span>
                    </label>
                    <textarea class="form-control form-control-3-4" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange" rows="5"></textarea>
                </div>
            </div>

            <details>
                <summary><span class="summary">What's 'No grade awarded'?</span></summary>
                <div class="panel panel-border-narrow" id="what-is-no-grade-awarded">
                    <p>
                        A grade is awarded when the apprentice successfully completes the apprenticeship standard. For some standards there will be no grade awarded. In these cases select 'No grade awarded'.
                    </p>
                </div>
            </details>

            <button type="submit" class="button">Continue</button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/CertificateAmend/_GradeScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/LastName.cshtml
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.Private.CertificateLastNameViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Apprentice's last name";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-lastname-form js-disable-on-submit" method="post" asp-action="LastName" asp-controller="CertificatePrivateLastName">
            @Html.HiddenFor(c => c.Id)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                    <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                        There is a problem
                    </h2>
                    <ul class="error-summary-list">
                        <li><a sfa-validation-for="LastName"></a></li>
                        <li><a sfa-validation-for="ReasonForChange"></a></li>
                    </ul>
                </div>
            }

                <div sfa-anyvalidationerror-class="after-error-summary">
                    <h1 class="heading-large">
                        What's the apprentice's last name?
                    </h1>

                    <div class="form-group" sfa-validation-for="LastName" sfa-validationerror-class="form-group-error">
                        <label for="LastName">
                            <span class="form-label-bold visually-hidden">Last Name</span>
                            <span class="form-hint">
                                For example, Hawkins
                            </span>
                            <span class="error-message" asp-validation-for="LastName"></span>
                        </label>
                        <input class="form-control" name="LastName" sfa-validation-for="LastName" sfa-validationerror-class="form-control-error" asp-for="LastName" type="text" maxlength="100" />
                    </div>

                    <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                        <label for="ReasonForChange">
                            <span class="form-label-bold">Reason for change</span>
                            <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                            <span class="error-message" asp-validation-for="ReasonForChange"></span>
                        </label>
                        <textarea class="form-control form-control-3-4" rows="5" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange"></textarea>
                    </div>
                </div>

            <button type="submit" class="button">Continue</button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/CertificateAmend/_LastNameScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/Recipient.cshtml
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.CertificateRecipientViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Recipient's name";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-recipient-form" type="post" asp-controller="CertificateRecipient" asp-method="Recipient">
            @Html.HiddenFor(c => c.Id)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                    <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                        There is a problem
                    </h2>
                    <ul class="error-summary-list">
                        <li><a sfa-validation-for="Name"></a></li>
                        <li><a sfa-validation-for="ReasonForChange"></a></li>
                    </ul>
                </div>
            }

                <fieldset sfa-anyvalidationerror-class="after-error-summary">
                    <legend id="Name">
                        <h1 class="heading-large">
                            Who will the certificate be sent to?
                        </h1>
                    </legend>

                    <div class="form-group" sfa-validation-for="Name" sfa-validationerror-class="form-group-error">
                        <label for="Name">
                            <span class="form-label-bold">Name</span>
                            <span class="form-hint">
                                For example, Joanna Smith
                            </span>
                            <span class="error-message" asp-validation-for="Name"></span>
                        </label>
                        <input class="form-control" name="Name" sfa-validation-for="Name" sfa-validationerror-class="form-control-error" asp-for="Name" type="text" />
                    </div>

                    <div class="form-group" sfa-validation-for="Dept" sfa-validationerror-class="form-group-error">
                        <label for="Dept">
                            <span class="form-label-bold">Department (optional)</span>
                            <span class="form-hint">
                                For example, human resources
                            </span>
                            <span class="error-message" asp-validation-for="Dept"></span>
                        </label>
                        <input class="form-control" name="Dept" sfa-validation-for="Dept" sfa-validationerror-class="form-control-error" asp-for="Dept" type="text" />
                    </div>

                    <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                        <label for="ReasonForChange">
                            <span class="form-label-bold">Reason for change</span>
                            <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                            <span class="error-message" asp-validation-for="ReasonForChange"></span>
                        </label>
                        <textarea class="form-control form-control-3-4" rows="5" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange"></textarea>
                    </div>
                </fieldset>

            <button type="submit" class="button">Continue</button>
        </form>

        <div>
            <a asp-action="Index" asp-controller="Search" class="link-back">Search Again</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/CertificateAmend/_RecipientScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/CertificateAmend/StandardCode.cshtml
@using Newtonsoft.Json
@model SFA.DAS.AssessorService.Web.Staff.ViewModels.Private.CertificateStandardCodeListViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Select standard";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="CertificateAmend" asp-action="Check" asp-route-certificateId=@Model.Id>Back</a>

        <form class="apprentice-standard-codes-form js-disable-on-submit" method="post" asp-action="StandardCode" asp-controller="CertificatePrivateStandardCode">
            @Html.HiddenFor(c => c.Id)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                    <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                        There is a problem
                    </h2>
                    <ul class="js-error-summary-list error-summary-list"></ul>
                    <ul class="error-summary-list">
                        <li><a sfa-validation-for="SelectedStandardCode"></a></li>
                        <li><a sfa-validation-for="ReasonForChange"></a></li>
                    </ul>
                </div>
            }

                <div sfa-anyvalidationerror-class="after-error-summary">
                    <h1 class="heading-large">
                        Search and select the standard
                    </h1>

                    <div class="form-group" sfa-validation-for="SelectedStandardCode" sfa-validationerror-class="form-group-error">
                        <label class="form-label" for="SelectedStandardCode">
                            <span class="form-label-bold visually-hidden">Standard Codes</span>
                            <span class="form-hint">
                                For example, Assistant accountant
                            </span>
                            <span class="error-message" asp-validation-for="SelectedStandardCode"></span>
                        </label>
                        <select class="form-control" asp-for="SelectedStandardCode" sfa-validation-for="SelectedStandardCode" sfa-validationerror-class="form-control-error" asp-items="@(new SelectList(Model.StandardCodes,"Value","Text"))">
                            <option value="">Please select one</option>
                        </select>
                    </div>

                    <div class="form-group" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-group-error">
                        <label for="ReasonForChange">
                            <span class="form-label-bold">Reason for change</span>
                            <span class="form-hint">Please could you provide more detail as to why this change is required.</span>
                            <span class="error-message" asp-validation-for="ReasonForChange"></span>
                        </label>
                        <textarea class="form-control form-control-3-4" rows="5" name="ReasonForChange" sfa-validation-for="ReasonForChange" sfa-validationerror-class="form-control-error" asp-for="ReasonForChange"></textarea>
                    </div>
                </div>

            <button type="submit" class="button">Continue</button>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{ await Html.RenderPartialAsync("~/Views/CertificateAmend/_StandardCodesScriptsPartial.cshtml"); }
}