src/SFA.DAS.AssessorService.Web.Staff/Models/ScheduleConfigViewModel.cs
using SFA.DAS.AssessorService.Web.Staff.Domain;
using SFA.DAS.AssessorService.Web.Staff.Helpers.DataAnnotations;
using System;
using System.ComponentModel.DataAnnotations;

namespace SFA.DAS.AssessorService.Web.Staff.Models
{
    public class ScheduleConfigViewModel
    {
        public Guid Id { get; set; }
        public DateTime RunTime { get; set; }
        public string Interval { get; set; }
        public ScheduleInterval? ScheduleInterval { get; set; }
        public bool IsRecurring { get; set; }
        public ScheduleJobType ScheduleType { get; set; }

        [FutureDate(GracePeriodInMinutes = 5, ErrorMessage = "Please enter a future date")]
        public DateTime Date => (Year < 1) ? DateTime.MinValue : new DateTime(Year, Month, Day, Hour, Minute, 0);
        [Range(1, 31, ErrorMessage = "Please enter a valid Day")]
        public int Day { get; set; }
        [Range(1, 12, ErrorMessage = "Please enter a valid Month")]
        public int Month { get; set; }
        [Range(2018, 9999, ErrorMessage = "Please enter a valid Year")]
        public int Year { get; set; }
        [Range(0, 23, ErrorMessage = "Please enter a valid Hour")]
        public int Hour { get; set; }
        [Range(0, 59, ErrorMessage = "Please enter a valid Minute")]
        public int Minute { get; set; }
    }
}

src/SFA.DAS.AssessorService.Web.Staff/Controllers/DashboardController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SFA.DAS.AssessorService.Web.Staff.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/SFA.DAS.AssessorService.Web.Staff/Controllers/ScheduleConfigController.cs
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.AssessorService.Domain.Entities;
using SFA.DAS.AssessorService.Domain.Extensions;
using SFA.DAS.AssessorService.Web.Staff.Domain;
using SFA.DAS.AssessorService.Web.Staff.Infrastructure;
using SFA.DAS.AssessorService.Web.Staff.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SFA.DAS.AssessorService.Web.Staff.Controllers
{
    [Authorize(Roles = Domain.Roles.OperationsTeam + "," + Domain.Roles.CertificationTeam)]
    public class ScheduleConfigController : Controller
    {
        private readonly ApiClient _apiClient;
        private readonly IHttpContextAccessor _contextAccessor;

        public ScheduleConfigController(ApiClient apiClient, IHttpContextAccessor contextAccessor)
        {
            _apiClient = apiClient;
            _contextAccessor = contextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ScheduleConfigViewModel> viewModels = new List<ScheduleConfigViewModel>();

            foreach(var schedule in await _apiClient.GetAllScheduledRun((int)ScheduleJobType.PrintRun))
            {
                ScheduleConfigViewModel viewModel = new ScheduleConfigViewModel
                {
                    Id = schedule.Id,
                    RunTime = schedule.RunTime.UtcToTimeZoneTime(),
                    Interval = schedule.Interval.HasValue ? TimeSpan.FromMinutes(schedule.Interval.Value).Humanize().Titleize() : "-",
                    IsRecurring = schedule.IsRecurring,
                    ScheduleType = (ScheduleJobType)schedule.ScheduleType,
                };

                if (Enum.TryParse<ScheduleInterval>(schedule.Interval.ToString(), out var scheduleInterval) && Enum.IsDefined(typeof(ScheduleInterval), scheduleInterval))
                {
                    viewModel.ScheduleInterval = scheduleInterval;
                }

                viewModels.Add(viewModel);
            }

            return View(viewModels);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid scheduleRunId)
        {
            var schedule = await _apiClient.GetScheduleRun(scheduleRunId);

            ScheduleConfigViewModel viewModel = new ScheduleConfigViewModel
            {
                Id = schedule.Id,
                RunTime = schedule.RunTime.UtcToTimeZoneTime(),
                Interval = schedule.Interval.HasValue ? TimeSpan.FromMinutes(schedule.Interval.Value).Humanize().Titleize() : "-",
                IsRecurring = schedule.IsRecurring,
                ScheduleType = (ScheduleJobType)schedule.ScheduleType,
            };

            if(Enum.TryParse<ScheduleInterval>(schedule.Interval.ToString(), out var scheduleInterval) && Enum.IsDefined(typeof(ScheduleInterval), scheduleInterval))
            {
                viewModel.ScheduleInterval = scheduleInterval;
            }

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ScheduleConfigViewModel viewModel)
        {
            if (viewModel != null)
            {
                await _apiClient.DeleteScheduleRun(viewModel.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            DateTime now = DateTime.UtcNow.UtcToTimeZoneTime();

            var viewModel = new ScheduleConfigViewModel
            {
                ScheduleType = ScheduleJobType.PrintRun,
                RunTime = now,
                Year = now.Year,
                Month = now.Month,
                Day = now.Day,
                Hour = now.Hour,
                Minute = now.Minute,
                IsRecurring = false,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ScheduleConfigViewModel viewModel)
        {
            if (viewModel != null)
            {
                // Binding to a nullable enum will cause a ModelState error
                ViewData.ModelState.Remove(nameof(viewModel.ScheduleInterval));

                if (!ViewData.ModelState.IsValid)
                {
                    return View(viewModel);
                }

                ScheduleRun schedule = new ScheduleRun
                {
                    ScheduleType = (ScheduleType)viewModel.ScheduleType,
                    RunTime = viewModel.Date.UtcFromTimeZoneTime(),
                    IsRecurring = viewModel.ScheduleInterval.HasValue,
                    Interval = (int?)viewModel.ScheduleInterval
                };

                await _apiClient.CreateScheduleRun(schedule);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> RunNow(int scheduleType)
        {
            var viewModel = new ScheduleConfigViewModel
            {
                ScheduleType = (ScheduleJobType)scheduleType,
                RunTime = DateTime.UtcNow.UtcToTimeZoneTime(),
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RunNow(ScheduleConfigViewModel viewModel)
        {
            if (viewModel != null)
            {
                await _apiClient.RunNowScheduledRun((int)viewModel.ScheduleType);
            }

            return RedirectToAction("Index");
        }
    }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/ScheduleConfig/Create.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, SFA.DAS.AssessorService.Web.Staff

@using SFA.DAS.AssessorService.Web.Staff.Domain
@model ScheduleConfigViewModel
@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Create Schedule";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a asp-action="Index" class="link-back">Go back</a>

        <h1 class="heading-xlarge">Create schedule</h1>

        <form class="apprentice-date-form" asp-action="Create" asp-controller="ScheduleConfig" method="post">
            @Html.HiddenFor(m => m.ScheduleType)

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
            <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    There is a problem
                </h2>
                <ul class="error-summary-list">
                    <li><a sfa-validation-for="Date"></a></li>
                    <li><a sfa-validation-for="Day"></a></li>
                    <li><a sfa-validation-for="Month"></a></li>
                    <li><a sfa-validation-for="Year"></a></li>
                    <li><a sfa-validation-for="Hour"></a></li>
                    <li><a sfa-validation-for="Minute"></a></li>
                </ul>
            </div>
            }



            <div sfa-anyvalidationerror-class="after-error-summary">
                <div id="Date">
                    <h2 class="heading-medium">
                        Run time date
                        <span class="form-hint">
                            For example, @(DateTime.UtcNow.AddDays(7).ToString("dd-MM-yyyy 12:00"))
                        </span>
                    </h2>
                </div>

                <div class="form-group error-message-container" sfa-anyvalidationerror-class="form-group-error">
                    <div class="form-date">
                        <div class="form-group form-group-day">
                            <label for="Day">Day</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Day" sfa-validationerror-class="form-control-error" asp-for="Day" maxlength="2" />
                        </div>

                        <div class="form-group form-group-month">
                            <label for="Month">Month</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Month" sfa-validationerror-class="form-control-error" asp-for="Month" maxlength="2" />
                        </div>

                        <div class="form-group form-group-year">
                            <label for="Year">Year</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Year" sfa-validationerror-class="form-control-error" asp-for="Year" maxlength="4" />
                        </div>

                        <div class="form-group form-group-hour">
                            <label for="Day">Hour</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Hour" sfa-validationerror-class="form-control-error" asp-for="Hour" maxlength="2" />
                        </div>

                        <div class="form-group form-group-minute">
                            <label for="Month">Minute</label>
                            <input class="form-control date-input js-integers-only" sfa-validation-for="Minute" sfa-validationerror-class="form-control-error" asp-for="Minute" maxlength="2" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <fieldset class="inline">
                    <legend>
                        <h2 class="heading-medium">
                            Is this a recurring job?
                        </h2>
                    </legend>

                    @foreach (var option in @Html.GetEnumSelectList<ScheduleInterval>())
                    {
                        <div class="multiple-choice" data-target="show-option-input">
                            <input asp-for="ScheduleInterval" id="options_@option.Text.Replace(" ", "")" type="radio" value="@option.Value" />
                            <label for="options_@option.Text.Replace(" ", "")">
                                @option.Text
                            </label>
                        </div>
                    }
                </fieldset>
            </div>

            <button type="submit" class="button">Continue</button>
        </form>

    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    @{await Html.RenderPartialAsync("~/Views/ScheduleConfig/_DateScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web.Staff/Views/ScheduleConfig/Delete.cshtml
@using Humanizer
@model ScheduleConfigViewModel
@{
    ViewBag.Title = "Delete Schedule";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-full">
        <a asp-action="Index" class="link-back">Go back</a>

        <h1 class="heading-large">Delete Schedule</h1>

        @if (@Model != null && @Model.Id != Guid.Empty)
        {
            <div class="form-group">
                <span class="bold">Please Confirm Deletion: </span>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>Is Recurring</th>
                        <th>Interval</th>
                        <th>Run Time</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.IsRecurring</td>
                        <td>@(Model.ScheduleInterval.HasValue ? Model.ScheduleInterval.Humanize(LetterCasing.Title) : Model.Interval)</td>
                        <td>@Model.RunTime</td>
                    </tr>
                </tbody>
            </table>

            <div>
                <form asp-action="Delete" asp-controller="ScheduleConfig" method="post">
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.ScheduleType)
                    <button class="button">Confirm</button>
                </form>
            </div>
        }
        else
        {
            <div class="form-group">
                <span class="bold">No Schedule Found.</span>
            </div>
        }

    </div>
</div>

src/SFA.DAS.AssessorService.Web.Staff/Views/ScheduleConfig/Index.cshtml
@using Humanizer
@model IList<ScheduleConfigViewModel>
@{
    ViewBag.Title = "Print Schedule";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a asp-action="Index" asp-controller="Dashboard" class="link-back">Return to dashboard</a>
        <h1 class="heading-xlarge">
            Print schedule
            <span class="heading-secondary">Next run scheduled: @if (Model.Any()) { @Model.First().RunTime; } else { @Html.Raw("Not Applicable"); }</span>
        </h1>
    </div>
</div>
<div class="grid-row">
    <div class="column-full">
        <div class="form-group">
            @if (!@Model.Where(m => !m.IsRecurring && m.RunTime <= DateTime.Now).Any())
            {
                <a asp-action="RunNow" asp-route-scheduleType="1" class="button">Run now</a>
            }
        </div>
        @if (@Model.Any())
        {
            <div class="form-group">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Is recurring</th>
                            <th>Interval</th>
                            <th>Run time</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var result in @Model)
                        {
                            <tr>
                                <td>@result.IsRecurring</td>
                                <td>@(result.ScheduleInterval.HasValue ? result.ScheduleInterval.Humanize(LetterCasing.Title) : result.Interval)</td>
                                <td>@result.RunTime</td>
                                <td class="numeric"><a asp-action="Delete" asp-route-scheduleRunId="@result.Id">Delete</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }

        <div class="form-group">
            <a asp-action="Create" class="button">Create new</a>
        </div>

    </div>
</div>

src/SFA.DAS.AssessorService.Web.Staff/Views/ScheduleConfig/RunNow.cshtml
@using Humanizer
@model ScheduleConfigViewModel
@{
    ViewBag.Title = "Run Schedule";
    Layout = "_Layout";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <a asp-action="Index" class="link-back">Go back</a>

        <h1 class="heading-xlarge">
            Run schedule now
            <span class="heading-secondary">Please confirm run now</span>

        </h1>
    </div>
</div>
<div class="grid-row">
    <div class="column-one-third">
        <div class="form-group">
            <table class="table">
                <thead>
                    <tr>
                        <th>Run time</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.RunTime</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <form asp-action="RunNow" asp-controller="ScheduleConfig" method="post">
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.ScheduleType)
            @Html.HiddenFor(m => m.RunTime)
            <button class="button">Confirm</button>
        </form>
    </div>
</div>

src/SFA.DAS.AssessorService.Web.Staff/Views/ScheduleConfig/_DateScriptsPartial.cshtml
<script>
  var epaoDateFormElement = $('.apprentice-date-form');
  var epaoDateValidationRulesObject = {
    rules: {
      Day: {
        required: true,
        number: true,
        range: [1, 31],
        isValidDate: {
          depends: function() {
            var year = $('#Year').val().length;
            return year === 4;
          }
        },
        noFutureDate: false,
        earliestDate: '1/1/2018'
      },
      Month: {
        required: true,
        number: true,
        range: [1, 12]
      },
      Year: {
        required: true,
        number: true,
        minlength: 4,
        maxlength: 4
      },
      Hour: {
        required: true,
        number: true,
        range: [1, 23]
        },
      Minute: {
        required: true,
        number: true,
        range: [0, 59]
      }
    },
    messages: {
      Day: {
        required: 'Enter the day',
        number: 'Day must be a number',
        range: 'Enter a valid day',
        isValidDate: 'Enter a valid date',
        noFutureDate: 'Date cannot be in the future',
        earliestDate: 'Date cannot be before 01 01 2018'
      },
      Month: {
        required: 'Enter the month',
        number: 'Month must be a number',
        range: 'Enter a valid month'
      },
      Year: {
        required: 'Enter the year',
        number: 'Year must be a number',
        minlength: 'Enter a valid year',
        maxlength: 'Enter a valid year'
      },
      Hour: {
        required: 'Enter the hour',
        number: 'Hour must be a number',
        range: 'Enter a valid hour'
      },
      Minute: {
        required: 'Enter the minute',
        number: 'Minute must be a number',
        range: 'Enter a valid minute'
      }
    }
  };

  GOVUK.epaoValidate(epaoDateFormElement, epaoDateValidationRulesObject);

</script>