src/SFA.DAS.AssessorService.Web/ViewModels/Search/ResultViewModel.cs
using System;

namespace SFA.DAS.AssessorService.Web.ViewModels.Search
{
    public class ResultViewModel
    {
        public string GivenNames { get; set; }
        public string FamilyName { get; set; }
        public string Uln { get; set; }
        public string Standard { get; set; }
        public string StdCode { get; set; } 
        public string OverallGrade { get; set; }
        public string CertificateReference { get; set; }
        public string Level { get; set; }
        public DateTime? SubmittedAt { get; set; }
        public string SubmittedBy { get; set; }
        public DateTime? AchDate { get; set; }
        public DateTime? LearnStartDate { get; set; }
        public bool ShowExtraInfo { get; set; }
    }
}

src/SFA.DAS.AssessorService.Web/ViewModels/Search/SearchRequestViewModel.cs
using System;
using System.Collections.Generic;
using SFA.DAS.AssessorService.Api.Types.Models;

namespace SFA.DAS.AssessorService.Web.ViewModels.Search
{
    public class SearchRequestViewModel
    {
        public string Uln { get; set; }
        public string Surname { get; set; }
        public bool IsPrivatelyFunded { get; set; }
        public IEnumerable<ResultViewModel> SearchResults { get; set; }
    }

    public class ChooseStandardViewModel
    {
        public string SelectedStandardCode { get; set; }
        public IEnumerable<ResultViewModel> SearchResults { get; set; }
    }

    public class SelectedStandardViewModel
    {
        public string GivenNames { get; set; }
        public string FamilyName { get; set; }
        public string Uln { get; set; }
        public string Standard { get; set; }
        public string StdCode { get; set; }
        public string OverallGrade { get; set; }
        public string CertificateReference { get; set; }
        public string Level { get; set; }
        public string SubmittedAt { get; set; }
        public string SubmittedBy { get; set; }
        public string LearnerStartDate { get; set; }
        public string AchievementDate { get; set; }

        public bool ShowExtraInfo { get; set; }
    }
}

src/SFA.DAS.AssessorService.Web/Controllers/CertificateController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SFA.DAS.AssessorService.Api.Types.Models.Certificates;
using SFA.DAS.AssessorService.Application.Api.Client.Clients;
using SFA.DAS.AssessorService.Web.Infrastructure;
using SFA.DAS.AssessorService.Web.ViewModels.Certificate;
using SFA.DAS.AssessorService.Web.ViewModels.Certificate.Private;

namespace SFA.DAS.AssessorService.Web.Controllers
{
    [Authorize]
    [CheckSession]
    [Route("certificate")]
    public class CertificateController : Controller
    {
        private readonly ILogger<CertificateController> _logger;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly ICertificateApiClient _certificateApiClient;
        private readonly IOrganisationsApiClient _organisationsApiClient;
        private readonly ISessionService _sessionService;

        public CertificateController(ILogger<CertificateController> logger, IHttpContextAccessor contextAccessor,
            ICertificateApiClient certificateApiClient, 
            IOrganisationsApiClient organisationsApiClient,
            ISessionService sessionService)
        {
            _logger = logger;
            _contextAccessor = contextAccessor;
            _certificateApiClient = certificateApiClient;
            _organisationsApiClient = organisationsApiClient;
            _sessionService = sessionService;
        }

        [HttpPost]
        public async Task<IActionResult> Start(CertificateStartViewModel vm)
        {
            _sessionService.Remove("CertificateSession");
            var ukprn = _contextAccessor.HttpContext.User.FindFirst("http://schemas.portal.com/ukprn")?.Value;
            var username = _contextAccessor.HttpContext.User
                .FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")?.Value;

            _logger.LogInformation(
                $"Start of Certificate Start for ULN {vm.Uln} and Standard Code: {vm.StdCode} by user {username}");

            var cert = await _certificateApiClient.Start(new StartCertificateRequest()
            {
                UkPrn = int.Parse(ukprn),
                StandardCode = vm.StdCode,
                Uln = vm.Uln,
                Username = username
            });

            var organisation = await _organisationsApiClient.Get(ukprn);

            var options = (await _certificateApiClient.GetOptions(cert.StandardCode)).Select(o => o.OptionName).ToList();

            _sessionService.Set("CertificateSession", new CertificateSession()
            {
                CertificateId = cert.Id,
                Uln = vm.Uln,
                StandardCode = vm.StdCode,
                Options = options
            });

            _logger.LogInformation(
                $"New Certificate received for ULN {vm.Uln} and Standard Code: {vm.StdCode} with ID {cert.Id}");

            return RedirectToAction("Declare", "CertificateDeclaration");
        }

        [HttpPost]
        [Route("certificate/private")]
        public async Task<IActionResult> StartPrivate(CertificateStartPrivateViewModel certificateStartPrivateViewModel)
        {
            _sessionService.Remove("CertificateSession");
            var ukprn = _contextAccessor.HttpContext.User.FindFirst("http://schemas.portal.com/ukprn")?.Value;
            var username = _contextAccessor.HttpContext.User
                .FindFirst("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")?.Value;

            _logger.LogInformation(
                $"Start of Private Certificate");

            var organisation = await _organisationsApiClient.Get(ukprn);

            var certificate = await _certificateApiClient.StartPrivate(new StartCertificatePrivateRequest()
            {
                UkPrn = int.Parse(ukprn),
                Uln = certificateStartPrivateViewModel.Uln,
                LastName = certificateStartPrivateViewModel.Surname,
                Username = username,
                EndPointAssessorOrganisationId = organisation.EndPointAssessorOrganisationId
            });
       
            _sessionService.Set("EndPointAsessorOrganisationId", organisation.EndPointAssessorOrganisationId);
           
           _sessionService.Set("CertificateSession", new CertificateSession()
            {
                CertificateId = certificate.Id,
                Uln = certificateStartPrivateViewModel.Uln
            });

            _logger.LogInformation(
                $"New Private Certificate received with ID {certificate.Id}");

            return RedirectToAction("FirstName", "CertificatePrivateFirstName");
        }
    }
}

src/SFA.DAS.AssessorService.Web/Controllers/SearchController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.AssessorService.Web.Constants;
using SFA.DAS.AssessorService.Web.Infrastructure;
using SFA.DAS.AssessorService.Web.Orchestrators.Search;
using SFA.DAS.AssessorService.Web.ViewModels.Search;

namespace SFA.DAS.AssessorService.Web.Controllers
{
    [Authorize]
    [CheckSession]
    [Route("[controller]/[action]")]
    public class SearchController : Controller
    {
        private readonly ISearchOrchestrator _searchOrchestrator;
        private readonly ISessionService _sessionService;

        public SearchController(ISearchOrchestrator searchOrchestrator, ISessionService sessionService)
        {
            _searchOrchestrator = searchOrchestrator;
            _sessionService = sessionService;
        }

        [HttpGet]
        [Route("/[controller]/")]
        [TypeFilter(typeof(MenuFilter), Arguments = new object[] { Pages.RecordAGrade })]
        public IActionResult Index()
        {
            _sessionService.Remove("SearchResults");
            _sessionService.Remove("SelectedStandard");
            _sessionService.Remove("SearchResultsChooseStandard");
            _sessionService.Remove("EndPointAsessorOrganisationId");
            return View("Index");
        }

        [HttpPost]
        [Route("/[controller]/")]
        public async Task<IActionResult> Index([FromForm] SearchRequestViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            if (vm.IsPrivatelyFunded)
            {
                return RedirectToAction("Index", "CertificatePrivateDeclaration", vm);
            }

            var result = await _searchOrchestrator.Search(vm);
            if (!result.SearchResults.Any()) return View("Index", vm);

            _sessionService.Set("SearchResults", result);
            
            if (result.SearchResults.Count() > 1)
            {
                GetChooseStandardViewModel(vm);
                return RedirectToAction("ChooseStandard");
            }

            GetSelectedStandardViewModel(result);
            return RedirectToAction("Result");
        }

        private void GetChooseStandardViewModel(SearchRequestViewModel vm)
        {
            var chooseStandardViewModel = new ChooseStandardViewModel
            {
                SearchResults = vm.SearchResults
            };

            _sessionService.Set("SearchResultsChooseStandard", chooseStandardViewModel);
        }

        private void GetSelectedStandardViewModel(SearchRequestViewModel result)
        {
            var resultViewModel = result.SearchResults.First();
            var selectedStandardViewModel = new SelectedStandardViewModel()
            {
                Standard = resultViewModel.Standard,
                StdCode = resultViewModel.StdCode,
                Uln = resultViewModel.Uln,
                GivenNames = resultViewModel.GivenNames,
                FamilyName = resultViewModel.FamilyName,
                CertificateReference = resultViewModel.CertificateReference,
                OverallGrade = resultViewModel.OverallGrade,
                Level = resultViewModel.Level,
                SubmittedAt = GetSubmittedAtString(resultViewModel.SubmittedAt),
                SubmittedBy = resultViewModel.SubmittedBy,
                LearnerStartDate = resultViewModel.LearnStartDate.GetValueOrDefault().ToString("d MMMM yyyy"),
                AchievementDate = resultViewModel.AchDate.GetValueOrDefault().ToString("d MMMM yyyy"),
                ShowExtraInfo = resultViewModel.ShowExtraInfo
            };

            _sessionService.Set("SelectedStandard", selectedStandardViewModel);
        }

        private string GetSubmittedAtString(DateTime? submittedAt)
        {
            return !submittedAt.HasValue ? "" : submittedAt.Value.ToString("d MMMM yyyy");
        }

        [HttpGet]
        public IActionResult Result()
        {
            var vm = _sessionService.Get<SelectedStandardViewModel>("SelectedStandard");
            if (vm == null)
            {
                return RedirectToAction("Index");
            }

            return View("Result", vm);
        }

        [HttpGet(Name = "choose")]
        public IActionResult ChooseStandard()
        {
            var vm = _sessionService.Get<ChooseStandardViewModel>("SearchResultsChooseStandard");
            if (vm == null)
            {
                return RedirectToAction("Index");
            }

            return View("ChooseStandard", vm);
        }

        [HttpPost(Name = "choose")]
        public IActionResult ChooseStandard(ChooseStandardViewModel chooseStandardViewModel)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = _sessionService.Get<ChooseStandardViewModel>("SearchResultsChooseStandard");
                return View("ChooseStandard", viewModel);
            }

            var vm = _sessionService.Get<SearchRequestViewModel>("SearchResults");
            if (vm == null)
            {
                return RedirectToAction("Index");
            }

            var selected = vm.SearchResults
                .Single(sr => sr.StdCode == chooseStandardViewModel.SelectedStandardCode);

            var selectedStandardViewModel = new SelectedStandardViewModel()
            {
                Standard = selected.Standard,
                StdCode = selected.StdCode,
                Uln = selected.Uln,
                GivenNames = selected.GivenNames,
                FamilyName = selected.FamilyName,
                CertificateReference = selected.CertificateReference,
                OverallGrade = selected.OverallGrade,
                Level = selected.Level,
                SubmittedAt = GetSubmittedAtString(selected.SubmittedAt),
                SubmittedBy = selected.SubmittedBy,
                LearnerStartDate = selected.LearnStartDate.GetValueOrDefault().ToString("d MMMM yyyy"),
                AchievementDate = selected.AchDate.GetValueOrDefault().ToString("d MMMM yyyy"),
                ShowExtraInfo = selected.ShowExtraInfo
            };

            _sessionService.Set("SelectedStandard", selectedStandardViewModel);
            
            return RedirectToAction("Result");
        }
    }
}

src/SFA.DAS.AssessorService.Web/Views/Search/ChooseStandard.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using SFA.DAS.AssessorService.Web.Utils
@inject IViewLocalizer Localizer
@model SFA.DAS.AssessorService.Web.ViewModels.Search.ChooseStandardViewModel

@{
    ViewBag.Title = (!ViewData.ModelState.IsValid ? "Error: " : "") + "Choose an apprenticeship";
    Layout = "_DashboardLayout";
}


<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="Search" asp-action="Index">Back</a>

        <form class="apprentice-choose-standard-form js-disable-on-submit" asp-controller="Search" asp-action="ChooseStandard" method="post">

            @* hidden with css by default *@
            <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                    @Localizer["ErrorsWithSubmission"]
                </h2>
                <ul class="js-error-summary-list error-summary-list"></ul>
            </div>

            @if (!ViewData.ModelState.IsValid)
            {
                <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
                    <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                        @Localizer["ErrorsWithSubmission"]
                    </h2>
                    <ul class="error-summary-list">
                        <li><a sfa-validation-for="SelectedStandardCode"></a></li>
                    </ul>
                </div>
            }

            <div sfa-anyvalidationerror-class="after-error-summary">
                <div>
                    <h1 class="heading-large">@Localizer["PageHeading"]</h1>
                    <p>@Localizer["PageDescription"]</p>
                    <ul class="list">
                        <li>
                            <p><span class="bold">Name:</span> @Model.SearchResults.First().GivenNames @Model.SearchResults.First().FamilyName</p>
                        </li>
                        <li>
                            <p><span class="bold"><abbr title="Unique learner number">ULN</abbr>:</span> @Model.SearchResults.First().Uln</p>
                        </li>
                    </ul>
                </div>

                <div class="form-group" sfa-validation-for="SelectedStandardCode" sfa-validationerror-class="form-group-error">
                    <div class="error-message-container" sfa-validation-for="SelectedStandardCode" >
                        <span class="error-message" asp-validation-for="SelectedStandardCode"></span>
                    </div>
                    @if (Model.SearchResults.Any(sr => sr.CertificateReference == null))
                    {
                        <div class="form-block">
                            <span class="form-label-bold">@Localizer.Pluralize("AssessmentsNotRecordedYet", Model.SearchResults.Count(sr => sr.CertificateReference == null) > 1)</span>
                        </div>
                        foreach (var result in Model.SearchResults.Where(sr => sr.CertificateReference == null))
                        {
                            <div class="multiple-choice">
                                <input id=@("standard_" + result.StdCode) type="radio" name="SelectedStandardCode" value="@result.StdCode">
                                <label for=@("standard_" + result.StdCode)>
                                    @result.Standard
                                </label>
                            </div>
                        }
                    }
                    @if (Model.SearchResults.Any(sr => sr.CertificateReference != null))
                    {
                        <div class="form-block">
                            <span class="form-label-bold">@Localizer.Pluralize("PreviouslyRecordedAssessments", Model.SearchResults.Count(sr => sr.CertificateReference != null) > 1)</span>
                        </div>
                        foreach (var result in Model.SearchResults.Where(sr => sr.CertificateReference != null))
                        {
                            <div class="multiple-choice">
                                <input id=@("standard_" + result.StdCode) type="radio" name="SelectedStandardCode" value="@result.StdCode">
                                <label for=@("standard_" + result.StdCode)>
                                    @result.Standard
                                </label>
                            </div>
                        }
                    }
                </div>
            </div>
            <div class="form-group">
                <button class="button" type="submit">@Localizer["SelectStandardButton"]</button>
            </div>
        </form>

        <p><a asp-controller="Search" asp-action="Index">Search again</a> if this isn’t the correct apprentice.</p>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("~/Views/Search/_ChooseStandardScriptsPartial.cshtml"); }
}

src/SFA.DAS.AssessorService.Web/Views/Search/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model SFA.DAS.AssessorService.Web.ViewModels.Search.SearchRequestViewModel

@{
    ViewBag.Title = (Model?.SearchResults != null && !Model.SearchResults.Any() ? "0 results found: " : !ViewData.ModelState.IsValid ? "Error: " : "") + "Record a grade";
    Layout = "_DashboardLayout";
}

<div>
    <div class="grid-row">
        <div class="column-two-thirds">

            @if (Model?.SearchResults != null)
            {
                if (!Model.SearchResults.Any())
                {
                    <a class="link-back" asp-controller="Search" asp-action="Index">Back</a>
                    <h1 class="heading-large">We cannot find the apprentice details</h1>

                    <p class="heading-medium">Check the:</p>
                    <ul class="list list-bullet">
                        <li>spelling of the last name</li>
                        <li><abbr title="Unique learner number">ULN</abbr> is correct for the apprentice</li>
                    </ul>

                    <p><a asp-controller="Search" asp-action="Index">Search again</a></p>

                    <details>
                        <summary><span class="summary">Why we can't find the apprentice</span></summary>
                        <div class="text panel panel-border-narrow" id="why-we-cant-find-the-apprentice">
                            <p>The most common reasons we can't find the apprentice are:</p>
                            <ul class="list list-bullet">
                                <li>the apprentice's details have changed, but the Individualised Learner Record (ILR) is not up to date</li>
                                <li>the <abbr title="Unique learner number">ULN</abbr> given to you by the training provider does not match what we have in our system</li>
                                <li>the apprenticeship is privately funded</li>
                            </ul>
                            <p>The correct details need to be agreed between you, the employer and the training provider. The training provider may need to update the Individualised Learner Record (ILR).</p>
                        </div>
                    </details>
                }
            }
            else
            {
                await Html.RenderPartialAsync("_SearchForm", Model);
            }

        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{ await Html.RenderPartialAsync("_SearchScriptsPartial"); }
}

src/SFA.DAS.AssessorService.Web/Views/Search/Result.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model SFA.DAS.AssessorService.Web.ViewModels.Search.SelectedStandardViewModel

@{
    ViewBag.Title = Model.CertificateReference == null ? "Confirm this is the correct apprentice" : "An assessment has already been recorded against this apprentice";
    Layout = "_DashboardLayout";
}


<div class="grid-row">
    <div class="column-two-thirds">
        <a class="link-back" asp-controller="Search" asp-action="ChooseStandard">Back</a>

        @if (Model.CertificateReference == null)
        {

            <h1 class="heading-large">Confirm this is the correct apprentice</h1>
            <form class="apprentice-search-result-form js-disable-on-submit" asp-controller="Certificate" asp-action="Start" method="post">
                <div class="form-group">
                    <ul>
                        <li>
                            <p><span class="bold">Name:</span> @Model.GivenNames @Model.FamilyName</p>
                        </li>
                        <li>
                            <p><span class="bold"><abbr title="Unique learner number">ULN</abbr>:</span> @Model.Uln</p>
                        </li>
                        <li>
                            <p><span class="bold">Standard:</span> @Model.Standard</p>
                        </li>
                        <li>
                            <p><span class="bold">Level:</span> @Model.Level</p>
                        </li>
                        <li>
                            <p><span class="bold">Learner start date:</span> @Model.LearnerStartDate</p>
                        </li>
                    </ul>
                    <p>If the name, standard or level is incorrect, you need to agree on the correct details along with the training provider and the employer. The training provider needs to then update the Individualised Learner Record (<abbr title="Individualised Learner Record">ILR</abbr>).</p>
                </div>

                @Html.HiddenFor(m => m.Uln)
                @Html.HiddenFor(m => m.StdCode)
                <div class="form-group">
                    <button class="button" type="submit">Confirm and continue</button>
                </div>
            </form>

            <p><a asp-controller="Search" asp-action="Index">Search again</a> if this isn't the correct apprentice.</p>
        }
        else
        {
            <h1 class="heading-large">An assessment has already been recorded against this apprentice</h1>
            <ul class="list">
                <li>
                    <p><span class="bold">Name:</span> @Model.GivenNames @Model.FamilyName</p>
                </li>
                <li>
                    <p><span class="bold"><abbr title="Unique learner number">ULN</abbr>:</span> @Model.Uln</p>
                </li>
                <li>
                    <p><span class="bold">Standard:</span> @Model.Standard</p>
                </li>
                <li>
                    <p><span class="bold">Level:</span> @Model.Level</p>
                </li>

                @if (Model.ShowExtraInfo)
                {

                    <li>
                        <p><span class="bold">Certificate number:</span> @Model.CertificateReference</p>
                    </li>
                    <li>
                        <p><span class="bold">Learner start date:</span> @Model.LearnerStartDate</p>
                    </li>
                    <li>
                        <p><span class="bold">Achievement Date:</span> @Model.AchievementDate</p>
                    </li>
                    <li>
                        <p><span class="bold">Grade:</span> @Model.OverallGrade</p>
                    </li>
                    <li>
                        <p><span class="bold">Recorded by:</span> @Model.SubmittedBy</p>
                    </li>
                    <li>
                        <p><span class="bold">Date recorded:</span> @Model.SubmittedAt</p>
                    </li>
                }

            </ul>

            <p><a asp-controller="Search" asp-action="Index">Search again</a></p>
        }

        
    </div>
</div>

src/SFA.DAS.AssessorService.Web/Views/Search/_SearchForm.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model SFA.DAS.AssessorService.Web.ViewModels.Search.SearchRequestViewModel

<form class="apprentice-search-form js-disable-on-submit" method="post" asp-controller="Search" asp-action="Index">

    @* hidden with css by default *@
    <div class="js-error-summary error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
        <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
            There's a problem
        </h2>
        <ul class="js-error-summary-list error-summary-list"></ul>
    </div>

    @if (!ViewData.ModelState.IsValid)
    {
        <div class="error-summary" role="alert" aria-labelledby="error-summary-heading" tabindex="-1">
            <h2 class="heading-medium error-summary-heading" id="error-summary-heading">
                There's a problem
            </h2>
            <ul class="error-summary-list">
                <li><a sfa-validation-for="Surname"></a></li>
                <li><a sfa-validation-for="Uln"></a></li>
            </ul>
        </div>
    }

    <h1 class="heading-large">Record a grade</h1>

    <div class="das-standout-box">
        <a href="https://www.smartsurvey.co.uk/s/certification-banner/" target="_blank">Complete our survey</a> to help us improve this section of the Apprenticeship assessment service.
    </div>
    
    <div class="info-summary">
        <h3 class="heading-medium">@Localizer["SearchInfoSummary"]</h3>
    </div>

    <div class="form-group" sfa-validation-for="Surname" sfa-validationerror-class="form-group-error">
        <label class="form-label" for="Surname">
            <span class="form-label-bold">@Localizer["Lastname"]</span>
            <span class="form-hint">@Localizer["LastnameHint"]</span>
            <span class="error-message" asp-validation-for="Surname"></span>
        </label>
        <input class="form-control" name="Surname" autocomplete="off" sfa-validation-for="Surname" sfa-validationerror-class="form-control-error" asp-for="Surname" type="text" maxlength="100" />
    </div>

    <div class="form-group" sfa-validation-for="Uln" sfa-validationerror-class="form-group-error">
        <label class="form-label" for="Uln">
            <span class="form-label-bold">Unique learner number (<abbr title="Unique learner number">ULN</abbr>)</span>
            <span class="form-hint">@Localizer["UlnHint"]</span>
            <span class="error-message" asp-validation-for="Uln"></span>
        </label>
        <input class="form-control js-integers-only" name="Uln" autocomplete="off" asp-for="Uln" type="text" sfa-validation-for="Uln" sfa-validationerror-class="form-control-error" maxlength="10" />
    </div>

    <details>
        <summary><span class="summary">What's a <abbr title="Unique learner number">ULN</abbr>?</span></summary>
        <div class="panel panel-border-narrow" id="what-is-a-unique-learner-number">
            <p>The <abbr title="Unique learner number">ULN</abbr> is a 10-digit reference number. It's used to access the online Personal Learning Record (<abbr title="Personal Learning Record">PLR</abbr>) of anyone aged 14 and over in UK education or training, including apprenticeships.</p>
        </div>
    </details>

    
    <div class="form-group">
        <div class="multiple-choice">
            <input name="IsPrivatelyFunded" asp-for="IsPrivatelyFunded" type="checkbox" type="checkbox" />
            <label for="IsPrivatelyFunded">@Localizer["PrivatelyFunded"]</label>
        </div>
    </div>
    <details> 
        <summary><span class="summary">How do I know if the apprenticeship is privately funded?</span></summary> 
        <div class="panel panel-border-narrow" id="what-is-a-unique-learner-number"> 
            <p>The training provider and employer will know if the apprenticeship is privately funded.</p> 
            <p>A privately funded apprenticeship doesn't receive government funding and isn't subject to ESFA funding rules.</p> 
        </div> 
    </details>
    

    <div class="form-group">
        <input class="button" id="button-search" type="submit" value="@Localizer["SearchButton"]">
    </div>

</form>

src/SFA.DAS.AssessorService.Web/Views/Search/_SearchScriptsPartial.cshtml
<script>
var epaoSearchFormElement = $('.apprentice-search-form');
var epaoSearchValidationRulesObject = {
  rules: {
    Surname: {
      required: true,
      maxlength: 100
    },
    Uln: {
      required: true,
      number: true,
      minlength: 10,
      maxlength: 10
    }
  },
  messages: {
    Surname: 'Enter the apprentice\'s last name',
    Uln: {
      required: 'Enter the apprentice\'s ULN',
      number: 'The apprentice\'s ULN should contain exactly 10 numbers',
      minlength: 'The apprentice\'s ULN should contain exactly 10 numbers',
      maxlength: 'The apprentice\'s ULN should contain exactly 10 numbers'
    }
  }
};

GOVUK.epaoValidate(epaoSearchFormElement, epaoSearchValidationRulesObject);
</script>